# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33f52e2de028937fc6404c576f67256470b920034eb52e555ec27ab764249cb8ebdc5390c688a3deb7687b8dd23ba976aac84445807df9da56668090ec60103f

test:
  secret_key_base: 5162fd427e3833f14ad896f8db15ce976fd262d3384538263ed028cec58b18a27a5f33da3ca0fb6eedad079962981dde3557975986f200a8b180a768df8304ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
